[package]
name = "cz"
version = "0.4.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = { version = "0.26", features = ["bundled"] }
regex = "1.5"
toml = "0.5"
